version: '3'
services:
    app:
        container_name: laravel-starter-app
        build: ./docker/php
        volumes:
            - ./src:/var/www
    web:
        image: nginx
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www
        depends_on:
            - app
    db:
        image: mysql:5.7
        container_name: laravel-starter-db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_ARROW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
            TZ: Tokyo/Asia
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
volumes:
    db_data: